var annotated_dup =
[
    [ "detail", "namespacedetail.html", [
      [ "container_input_adapter_factory_impl", "namespacedetail_1_1container__input__adapter__factory__impl.html", [
        [ "container_input_adapter_factory", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
        [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3983614ac0e8828aa386ca24b1ddc2bd1.html", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3983614ac0e8828aa386ca24b1ddc2bd1" ]
      ] ],
      [ "dtoa_impl", "namespacedetail_1_1dtoa__impl.html", [
        [ "boundaries", "structdetail_1_1dtoa__impl_1_1boundaries.html", "structdetail_1_1dtoa__impl_1_1boundaries" ],
        [ "cached_power", "structdetail_1_1dtoa__impl_1_1cached__power.html", "structdetail_1_1dtoa__impl_1_1cached__power" ],
        [ "diyfp", "structdetail_1_1dtoa__impl_1_1diyfp.html", "structdetail_1_1dtoa__impl_1_1diyfp" ]
      ] ],
      [ "utility_internal", "namespacedetail_1_1utility__internal.html", [
        [ "Extend", "structdetail_1_1utility__internal_1_1Extend.html", null ],
        [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_010_01_4.html", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_010_01_4" ],
        [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_011_01_4.html", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_011_01_4" ],
        [ "Gen", "structdetail_1_1utility__internal_1_1Gen.html", "structdetail_1_1utility__internal_1_1Gen" ],
        [ "Gen< T, 0 >", "structdetail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4.html", "structdetail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4" ]
      ] ],
      [ "actual_object_comparator", "structdetail_1_1actual__object__comparator.html", "structdetail_1_1actual__object__comparator" ],
      [ "binary_reader", "classdetail_1_1binary__reader.html", "classdetail_1_1binary__reader" ],
      [ "binary_writer", "classdetail_1_1binary__writer.html", "classdetail_1_1binary__writer" ],
      [ "char_traits", "structdetail_1_1char__traits.html", null ],
      [ "char_traits< signed char >", "structdetail_1_1char__traits_3_01signed_01char_01_4.html", "structdetail_1_1char__traits_3_01signed_01char_01_4" ],
      [ "char_traits< unsigned char >", "structdetail_1_1char__traits_3_01unsigned_01char_01_4.html", "structdetail_1_1char__traits_3_01unsigned_01char_01_4" ],
      [ "conjunction", "structdetail_1_1conjunction.html", null ],
      [ "conjunction< B >", "structdetail_1_1conjunction_3_01B_01_4.html", null ],
      [ "conjunction< B, Bn... >", "structdetail_1_1conjunction_3_01B_00_01Bn_8_8_8_01_4.html", null ],
      [ "detector", "structdetail_1_1detector.html", "structdetail_1_1detector" ],
      [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structdetail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", "structdetail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4" ],
      [ "exception", "classdetail_1_1exception.html", "classdetail_1_1exception" ],
      [ "external_constructor", "structdetail_1_1external__constructor.html", null ],
      [ "external_constructor< value_t::array >", "structdetail_1_1external__constructor_3_01value__t_1_1array_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1array_01_4" ],
      [ "external_constructor< value_t::binary >", "structdetail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1binary_01_4" ],
      [ "external_constructor< value_t::boolean >", "structdetail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1boolean_01_4" ],
      [ "external_constructor< value_t::number_float >", "structdetail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1number__float_01_4" ],
      [ "external_constructor< value_t::number_integer >", "structdetail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1number__integer_01_4" ],
      [ "external_constructor< value_t::number_unsigned >", "structdetail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4" ],
      [ "external_constructor< value_t::object >", "structdetail_1_1external__constructor_3_01value__t_1_1object_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1object_01_4" ],
      [ "external_constructor< value_t::string >", "structdetail_1_1external__constructor_3_01value__t_1_1string_01_4.html", "structdetail_1_1external__constructor_3_01value__t_1_1string_01_4" ],
      [ "file_input_adapter", "classdetail_1_1file__input__adapter.html", "classdetail_1_1file__input__adapter" ],
      [ "from_json_fn", "structdetail_1_1from__json__fn.html", "structdetail_1_1from__json__fn" ],
      [ "has_from_json", "structdetail_1_1has__from__json.html", null ],
      [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html", "structdetail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4" ],
      [ "has_key_compare", "structdetail_1_1has__key__compare.html", null ],
      [ "has_non_default_from_json", "structdetail_1_1has__non__default__from__json.html", null ],
      [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_912047717fa07cfa9d99fe9eafcf1e11e.html", "structdetail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_912047717fa07cfa9d99fe9eafcf1e11e" ],
      [ "has_to_json", "structdetail_1_1has__to__json.html", null ],
      [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html", "structdetail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4" ],
      [ "identity_tag", "structdetail_1_1identity__tag.html", null ],
      [ "input_stream_adapter", "classdetail_1_1input__stream__adapter.html", "classdetail_1_1input__stream__adapter" ],
      [ "integer_sequence", "structdetail_1_1integer__sequence.html", "structdetail_1_1integer__sequence" ],
      [ "internal_iterator", "structdetail_1_1internal__iterator.html", "structdetail_1_1internal__iterator" ],
      [ "invalid_iterator", "classdetail_1_1invalid__iterator.html", "classdetail_1_1invalid__iterator" ],
      [ "is_basic_json", "structdetail_1_1is__basic__json.html", null ],
      [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structdetail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
      [ "is_basic_json_context", "structdetail_1_1is__basic__json__context.html", null ],
      [ "is_c_string", "structdetail_1_1is__c__string.html", null ],
      [ "is_comparable", "structdetail_1_1is__comparable.html", null ],
      [ "is_comparable< Compare, A, B, void_t< decltype(std::declval< Compare >()(std::declval< A >(), std::declval< B >())), decltype(std::declval< Compare >()(std::declval< B >(), std::declval< A >()))> >", "structdetail_1_1is__comparable_3_01Compare_00_01A_00_01B_00_01void__t_3_01decltype_07std_1_1decle5e3400d312093eca0a7154409c6a227.html", null ],
      [ "is_compatible_array_type", "structdetail_1_1is__compatible__array__type.html", null ],
      [ "is_compatible_array_type_impl", "structdetail_1_1is__compatible__array__type__impl.html", null ],
      [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structdetail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleArrayType_00_ba7b30737b5c65ad9adb609a3762b85a.html", "structdetail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleArrayType_00_ba7b30737b5c65ad9adb609a3762b85a" ],
      [ "is_compatible_integer_type", "structdetail_1_1is__compatible__integer__type.html", null ],
      [ "is_compatible_integer_type_impl", "structdetail_1_1is__compatible__integer__type__impl.html", null ],
      [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structdetail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01CompatibleNumberInt5b484fcfc2d1ae63b1211da72eabe33b.html", "structdetail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01CompatibleNumberInt5b484fcfc2d1ae63b1211da72eabe33b" ],
      [ "is_compatible_object_type", "structdetail_1_1is__compatible__object__type.html", null ],
      [ "is_compatible_object_type_impl", "structdetail_1_1is__compatible__object__type__impl.html", null ],
      [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structdetail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01CompatibleObjectType_01530c59509aa77cdb5f1e95cf109944f.html", "structdetail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01CompatibleObjectType_01530c59509aa77cdb5f1e95cf109944f" ],
      [ "is_compatible_string_type", "structdetail_1_1is__compatible__string__type.html", "structdetail_1_1is__compatible__string__type" ],
      [ "is_compatible_type", "structdetail_1_1is__compatible__type.html", null ],
      [ "is_compatible_type_impl", "structdetail_1_1is__compatible__type__impl.html", null ],
      [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structdetail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_01enable__if67e19080e9bd0cd565bd49f604895399.html", "structdetail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_01enable__if67e19080e9bd0cd565bd49f604895399" ],
      [ "is_complete_type", "structdetail_1_1is__complete__type.html", null ],
      [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structdetail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
      [ "is_constructible", "structdetail_1_1is__constructible.html", null ],
      [ "is_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
      [ "is_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "is_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
      [ "is_constructible< std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "is_constructible_array_type", "structdetail_1_1is__constructible__array__type.html", null ],
      [ "is_constructible_array_type_impl", "structdetail_1_1is__constructible__array__type__impl.html", null ],
      [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTy3a773789b90b07cf1d15e358c6d585ac.html", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTy3a773789b90b07cf1d15e358c6d585ac" ],
      [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTyff4af2af9684a1cc8580410ec8c319a4.html", null ],
      [ "is_constructible_object_type", "structdetail_1_1is__constructible__object__type.html", null ],
      [ "is_constructible_object_type_impl", "structdetail_1_1is__constructible__object__type__impl.html", null ],
      [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structdetail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01ConstructibleObject435b838380c31b9738383402f7bb5943.html", "structdetail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01ConstructibleObject435b838380c31b9738383402f7bb5943" ],
      [ "is_constructible_string_type", "structdetail_1_1is__constructible__string__type.html", "structdetail_1_1is__constructible__string__type" ],
      [ "is_constructible_tuple", "structdetail_1_1is__constructible__tuple.html", null ],
      [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structdetail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "is_default_constructible", "structdetail_1_1is__default__constructible.html", null ],
      [ "is_default_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
      [ "is_default_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "is_default_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
      [ "is_default_constructible< std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "is_detected_lazy", "structdetail_1_1is__detected__lazy.html", null ],
      [ "is_getable", "structdetail_1_1is__getable.html", "structdetail_1_1is__getable" ],
      [ "is_iterator_of_multibyte", "structdetail_1_1is__iterator__of__multibyte.html", "structdetail_1_1is__iterator__of__multibyte" ],
      [ "is_iterator_traits", "structdetail_1_1is__iterator__traits.html", null ],
      [ "is_iterator_traits< iterator_traits< T > >", "structdetail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4.html", "structdetail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4" ],
      [ "is_json_iterator_of", "structdetail_1_1is__json__iterator__of.html", null ],
      [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::const_iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1const__iterator_01_4.html", null ],
      [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1iterator_01_4.html", null ],
      [ "is_json_ref", "structdetail_1_1is__json__ref.html", null ],
      [ "is_json_ref< json_ref< T > >", "structdetail_1_1is__json__ref_3_01json__ref_3_01T_01_4_01_4.html", null ],
      [ "is_ordered_map", "structdetail_1_1is__ordered__map.html", "structdetail_1_1is__ordered__map" ],
      [ "is_range", "structdetail_1_1is__range.html", "structdetail_1_1is__range" ],
      [ "is_sax", "structdetail_1_1is__sax.html", "structdetail_1_1is__sax" ],
      [ "is_sax_static_asserts", "structdetail_1_1is__sax__static__asserts.html", "structdetail_1_1is__sax__static__asserts" ],
      [ "is_specialization_of", "structdetail_1_1is__specialization__of.html", null ],
      [ "is_specialization_of< Primary, Primary< Args... > >", "structdetail_1_1is__specialization__of_3_01Primary_00_01Primary_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "is_transparent", "structdetail_1_1is__transparent.html", null ],
      [ "iter_impl", "classdetail_1_1iter__impl.html", "classdetail_1_1iter__impl" ],
      [ "iteration_proxy", "classdetail_1_1iteration__proxy.html", "classdetail_1_1iteration__proxy" ],
      [ "iteration_proxy_value", "classdetail_1_1iteration__proxy__value.html", "classdetail_1_1iteration__proxy__value" ],
      [ "iterator_input_adapter", "classdetail_1_1iterator__input__adapter.html", "classdetail_1_1iterator__input__adapter" ],
      [ "iterator_input_adapter_factory", "structdetail_1_1iterator__input__adapter__factory.html", "structdetail_1_1iterator__input__adapter__factory" ],
      [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structdetail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__t_3_01is__it379df2cab17a32e3e44924a3e0b8f300.html", "structdetail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__t_3_01is__it379df2cab17a32e3e44924a3e0b8f300" ],
      [ "iterator_traits", "structdetail_1_1iterator__traits.html", null ],
      [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structdetail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4.html", "structdetail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4" ],
      [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structdetail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ],
      [ "iterator_types", "structdetail_1_1iterator__types.html", null ],
      [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structdetail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference__type_00_01tce77e1bdc2e5b392df295e4bdf270278.html", "structdetail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference__type_00_01tce77e1bdc2e5b392df295e4bdf270278" ],
      [ "json_default_base", "structdetail_1_1json__default__base.html", null ],
      [ "json_ref", "classdetail_1_1json__ref.html", "classdetail_1_1json__ref" ],
      [ "json_reverse_iterator", "classdetail_1_1json__reverse__iterator.html", "classdetail_1_1json__reverse__iterator" ],
      [ "json_sax_acceptor", "classdetail_1_1json__sax__acceptor.html", "classdetail_1_1json__sax__acceptor" ],
      [ "json_sax_dom_callback_parser", "classdetail_1_1json__sax__dom__callback__parser.html", "classdetail_1_1json__sax__dom__callback__parser" ],
      [ "json_sax_dom_parser", "classdetail_1_1json__sax__dom__parser.html", "classdetail_1_1json__sax__dom__parser" ],
      [ "lexer", "classdetail_1_1lexer.html", "classdetail_1_1lexer" ],
      [ "lexer_base", "classdetail_1_1lexer__base.html", "classdetail_1_1lexer__base" ],
      [ "make_void", "structdetail_1_1make__void.html", "structdetail_1_1make__void" ],
      [ "negation", "structdetail_1_1negation.html", null ],
      [ "nonesuch", "structdetail_1_1nonesuch.html", "structdetail_1_1nonesuch" ],
      [ "other_error", "classdetail_1_1other__error.html", "classdetail_1_1other__error" ],
      [ "out_of_range", "classdetail_1_1out__of__range.html", "classdetail_1_1out__of__range" ],
      [ "output_adapter", "classdetail_1_1output__adapter.html", "classdetail_1_1output__adapter" ],
      [ "output_adapter_protocol", "structdetail_1_1output__adapter__protocol.html", "structdetail_1_1output__adapter__protocol" ],
      [ "output_stream_adapter", "classdetail_1_1output__stream__adapter.html", "classdetail_1_1output__stream__adapter" ],
      [ "output_string_adapter", "classdetail_1_1output__string__adapter.html", "classdetail_1_1output__string__adapter" ],
      [ "output_vector_adapter", "classdetail_1_1output__vector__adapter.html", "classdetail_1_1output__vector__adapter" ],
      [ "parse_error", "classdetail_1_1parse__error.html", "classdetail_1_1parse__error" ],
      [ "parser", "classdetail_1_1parser.html", "classdetail_1_1parser" ],
      [ "position_t", "structdetail_1_1position__t.html", "structdetail_1_1position__t" ],
      [ "primitive_iterator_t", "classdetail_1_1primitive__iterator__t.html", "classdetail_1_1primitive__iterator__t" ],
      [ "priority_tag", "structdetail_1_1priority__tag.html", null ],
      [ "priority_tag< 0 >", "structdetail_1_1priority__tag_3_010_01_4.html", null ],
      [ "serializer", "classdetail_1_1serializer.html", "classdetail_1_1serializer" ],
      [ "span_input_adapter", "classdetail_1_1span__input__adapter.html", "classdetail_1_1span__input__adapter" ],
      [ "static_const", "structdetail_1_1static__const.html", "structdetail_1_1static__const" ],
      [ "to_json_fn", "structdetail_1_1to__json__fn.html", "structdetail_1_1to__json__fn" ],
      [ "type_error", "classdetail_1_1type__error.html", "classdetail_1_1type__error" ],
      [ "value_in_range_of_impl1", "structdetail_1_1value__in__range__of__impl1.html", null ],
      [ "value_in_range_of_impl1< OfType, T, false >", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01false_01_4.html", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01false_01_4" ],
      [ "value_in_range_of_impl1< OfType, T, true >", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01true_01_4.html", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01true_01_4" ],
      [ "value_in_range_of_impl2", "structdetail_1_1value__in__range__of__impl2.html", null ],
      [ "value_in_range_of_impl2< OfType, T, false, false >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01false_01_4.html", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01false_01_4" ],
      [ "value_in_range_of_impl2< OfType, T, false, true >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01true_01_4.html", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01true_01_4" ],
      [ "value_in_range_of_impl2< OfType, T, true, false >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01false_01_4.html", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01false_01_4" ],
      [ "value_in_range_of_impl2< OfType, T, true, true >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01true_01_4.html", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01true_01_4" ],
      [ "wide_string_input_adapter", "classdetail_1_1wide__string__input__adapter.html", "classdetail_1_1wide__string__input__adapter" ],
      [ "wide_string_input_helper", "structdetail_1_1wide__string__input__helper.html", null ],
      [ "wide_string_input_helper< BaseInputAdapter, 2 >", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4.html", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4" ],
      [ "wide_string_input_helper< BaseInputAdapter, 4 >", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4.html", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4" ]
    ] ],
    [ "lsp", "namespacelsp.html", [
      [ "CompletionItem", "structlsp_1_1CompletionItem.html", "structlsp_1_1CompletionItem" ],
      [ "CompletionList", "structlsp_1_1CompletionList.html", "structlsp_1_1CompletionList" ],
      [ "CompletionOptions", "structlsp_1_1CompletionOptions.html", "structlsp_1_1CompletionOptions" ],
      [ "CompletionParams", "structlsp_1_1CompletionParams.html", "structlsp_1_1CompletionParams" ],
      [ "CompletionProvider", "classlsp_1_1CompletionProvider.html", "classlsp_1_1CompletionProvider" ],
      [ "DefinitionParams", "structlsp_1_1DefinitionParams.html", "structlsp_1_1DefinitionParams" ],
      [ "DefinitionProvider", "classlsp_1_1DefinitionProvider.html", "classlsp_1_1DefinitionProvider" ],
      [ "DidChangeTextDocumentParams", "structlsp_1_1DidChangeTextDocumentParams.html", "structlsp_1_1DidChangeTextDocumentParams" ],
      [ "DidCloseTextDocumentParams", "structlsp_1_1DidCloseTextDocumentParams.html", "structlsp_1_1DidCloseTextDocumentParams" ],
      [ "DidOpenTextDocumentParams", "structlsp_1_1DidOpenTextDocumentParams.html", "structlsp_1_1DidOpenTextDocumentParams" ],
      [ "Document", "structlsp_1_1Document.html", "structlsp_1_1Document" ],
      [ "DocumentStore", "classlsp_1_1DocumentStore.html", "classlsp_1_1DocumentStore" ],
      [ "DocumentSymbol", "structlsp_1_1DocumentSymbol.html", "structlsp_1_1DocumentSymbol" ],
      [ "DocumentSymbolParams", "structlsp_1_1DocumentSymbolParams.html", "structlsp_1_1DocumentSymbolParams" ],
      [ "Hover", "structlsp_1_1Hover.html", "structlsp_1_1Hover" ],
      [ "HoverParams", "structlsp_1_1HoverParams.html", "structlsp_1_1HoverParams" ],
      [ "HoverProvider", "classlsp_1_1HoverProvider.html", "classlsp_1_1HoverProvider" ],
      [ "InitializeResult", "structlsp_1_1InitializeResult.html", "structlsp_1_1InitializeResult" ],
      [ "Location", "structlsp_1_1Location.html", "structlsp_1_1Location" ],
      [ "LspDiagnostic", "structlsp_1_1LspDiagnostic.html", "structlsp_1_1LspDiagnostic" ],
      [ "LspServer", "classlsp_1_1LspServer.html", "classlsp_1_1LspServer" ],
      [ "MarkupContent", "structlsp_1_1MarkupContent.html", "structlsp_1_1MarkupContent" ],
      [ "Position", "structlsp_1_1Position.html", "structlsp_1_1Position" ],
      [ "ProjectIndex", "classlsp_1_1ProjectIndex.html", "classlsp_1_1ProjectIndex" ],
      [ "PublishDiagnosticsParams", "structlsp_1_1PublishDiagnosticsParams.html", "structlsp_1_1PublishDiagnosticsParams" ],
      [ "Range", "structlsp_1_1Range.html", "structlsp_1_1Range" ],
      [ "ReferenceParams", "structlsp_1_1ReferenceParams.html", "structlsp_1_1ReferenceParams" ],
      [ "ServerCapabilities", "structlsp_1_1ServerCapabilities.html", "structlsp_1_1ServerCapabilities" ],
      [ "ServerInfo", "structlsp_1_1ServerInfo.html", "structlsp_1_1ServerInfo" ],
      [ "Symbol", "structlsp_1_1Symbol.html", "structlsp_1_1Symbol" ],
      [ "SymbolExtractor", "classlsp_1_1SymbolExtractor.html", "classlsp_1_1SymbolExtractor" ],
      [ "TextDocumentContentChangeEvent", "structlsp_1_1TextDocumentContentChangeEvent.html", "structlsp_1_1TextDocumentContentChangeEvent" ],
      [ "TextDocumentIdentifier", "structlsp_1_1TextDocumentIdentifier.html", "structlsp_1_1TextDocumentIdentifier" ],
      [ "TextDocumentItem", "structlsp_1_1TextDocumentItem.html", "structlsp_1_1TextDocumentItem" ],
      [ "TextDocumentSyncOptions", "structlsp_1_1TextDocumentSyncOptions.html", "structlsp_1_1TextDocumentSyncOptions" ],
      [ "VersionedTextDocumentIdentifier", "structlsp_1_1VersionedTextDocumentIdentifier.html", "structlsp_1_1VersionedTextDocumentIdentifier" ]
    ] ],
    [ "magic_enum", "namespacemagic__enum.html", [
      [ "customize", "namespacemagic__enum_1_1customize.html", [
        [ "customize_t", "classmagic__enum_1_1customize_1_1customize__t.html", "classmagic__enum_1_1customize_1_1customize__t" ],
        [ "enum_range", "structmagic__enum_1_1customize_1_1enum__range.html", "structmagic__enum_1_1customize_1_1enum__range" ]
      ] ],
      [ "detail", "namespacemagic__enum_1_1detail.html", [
        [ "case_insensitive", "classmagic__enum_1_1detail_1_1case__insensitive.html", "classmagic__enum_1_1detail_1_1case__insensitive" ],
        [ "enable_if_enum", "structmagic__enum_1_1detail_1_1enable__if__enum.html", null ],
        [ "enable_if_enum< true, R >", "structmagic__enum_1_1detail_1_1enable__if__enum_3_01true_00_01R_01_4.html", "structmagic__enum_1_1detail_1_1enable__if__enum_3_01true_00_01R_01_4" ],
        [ "has_is_flags", "structmagic__enum_1_1detail_1_1has__is__flags.html", null ],
        [ "has_is_flags< T, std::void_t< decltype(customize::enum_range< T >::is_flags)> >", "structmagic__enum_1_1detail_1_1has__is__flags_3_01T_00_01std_1_1void__t_3_01decltype_07customize13d690b0add06bd55a4dd8d99f1b8c51.html", null ],
        [ "is_reflected", "structmagic__enum_1_1detail_1_1is__reflected.html", null ],
        [ "is_scoped_enum", "structmagic__enum_1_1detail_1_1is__scoped__enum.html", null ],
        [ "is_scoped_enum< T, true >", "structmagic__enum_1_1detail_1_1is__scoped__enum_3_01T_00_01true_01_4.html", null ],
        [ "is_unscoped_enum", "structmagic__enum_1_1detail_1_1is__unscoped__enum.html", null ],
        [ "is_unscoped_enum< T, true >", "structmagic__enum_1_1detail_1_1is__unscoped__enum_3_01T_00_01true_01_4.html", null ],
        [ "range_max", "structmagic__enum_1_1detail_1_1range__max.html", null ],
        [ "range_max< T, std::void_t< decltype(customize::enum_range< T >::max)> >", "structmagic__enum_1_1detail_1_1range__max_3_01T_00_01std_1_1void__t_3_01decltype_07customize_1_1376f6eb50191a2e253cb2b0e1d2386a7.html", null ],
        [ "range_min", "structmagic__enum_1_1detail_1_1range__min.html", null ],
        [ "range_min< T, std::void_t< decltype(customize::enum_range< T >::min)> >", "structmagic__enum_1_1detail_1_1range__min_3_01T_00_01std_1_1void__t_3_01decltype_07customize_1_14afc0df766d6bd32918519501ffe6473.html", null ],
        [ "static_str", "classmagic__enum_1_1detail_1_1static__str.html", "classmagic__enum_1_1detail_1_1static__str" ],
        [ "static_str< 0 >", "classmagic__enum_1_1detail_1_1static__str_3_010_01_4.html", "classmagic__enum_1_1detail_1_1static__str_3_010_01_4" ],
        [ "str_view", "structmagic__enum_1_1detail_1_1str__view.html", "structmagic__enum_1_1detail_1_1str__view" ],
        [ "supported", "structmagic__enum_1_1detail_1_1supported.html", null ],
        [ "underlying_type", "structmagic__enum_1_1detail_1_1underlying__type.html", null ],
        [ "underlying_type< T, true >", "structmagic__enum_1_1detail_1_1underlying__type_3_01T_00_01true_01_4.html", null ],
        [ "valid_count_t", "structmagic__enum_1_1detail_1_1valid__count__t.html", "structmagic__enum_1_1detail_1_1valid__count__t" ]
      ] ],
      [ "is_scoped_enum", "structmagic__enum_1_1is__scoped__enum.html", null ],
      [ "is_unscoped_enum", "structmagic__enum_1_1is__unscoped__enum.html", null ],
      [ "underlying_type", "structmagic__enum_1_1underlying__type.html", null ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< nlohmann::NLOHMANN_BASIC_JSON_TPL >", "structstd_1_1hash_3_01nlohmann_1_1NLOHMANN__BASIC__JSON__TPL_01_4.html", "structstd_1_1hash_3_01nlohmann_1_1NLOHMANN__BASIC__JSON__TPL_01_4" ],
      [ "less< ::nlohmann::detail::value_t >", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4" ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ]
    ] ],
    [ "yoi", "namespaceyoi.html", [
      [ "abstractExpr", "classyoi_1_1abstractExpr.html", "classyoi_1_1abstractExpr" ],
      [ "addExpr", "classyoi_1_1addExpr.html", "classyoi_1_1addExpr" ],
      [ "AnalysisState", "structyoi_1_1AnalysisState.html", "structyoi_1_1AnalysisState" ],
      [ "andExpr", "classyoi_1_1andExpr.html", "classyoi_1_1andExpr" ],
      [ "AST", "classyoi_1_1AST.html", "classyoi_1_1AST" ],
      [ "basicLiterals", "classyoi_1_1basicLiterals.html", "classyoi_1_1basicLiterals" ],
      [ "bracedInitalizerList", "classyoi_1_1bracedInitalizerList.html", "classyoi_1_1bracedInitalizerList" ],
      [ "breakStmt", "classyoi_1_1breakStmt.html", null ],
      [ "BuiltinModuleBuilder", "classyoi_1_1BuiltinModuleBuilder.html", "classyoi_1_1BuiltinModuleBuilder" ],
      [ "CallGraph", "structyoi_1_1CallGraph.html", "structyoi_1_1CallGraph" ],
      [ "catchParam", "classyoi_1_1catchParam.html", "classyoi_1_1catchParam" ],
      [ "ccObjectLinker", "classyoi_1_1ccObjectLinker.html", "classyoi_1_1ccObjectLinker" ],
      [ "clObjectLinker", "classyoi_1_1clObjectLinker.html", "classyoi_1_1clObjectLinker" ],
      [ "codeBlock", "classyoi_1_1codeBlock.html", "classyoi_1_1codeBlock" ],
      [ "CodegenObjectCache", "classyoi_1_1CodegenObjectCache.html", "classyoi_1_1CodegenObjectCache" ],
      [ "CodegenObjectCacheEntry", "structyoi_1_1CodegenObjectCacheEntry.html", "structyoi_1_1CodegenObjectCacheEntry" ],
      [ "CodegenTaskDispatcher", "classyoi_1_1CodegenTaskDispatcher.html", "classyoi_1_1CodegenTaskDispatcher" ],
      [ "compilerContext", "classyoi_1_1compilerContext.html", "classyoi_1_1compilerContext" ],
      [ "conceptDefinition", "classyoi_1_1conceptDefinition.html", "classyoi_1_1conceptDefinition" ],
      [ "conceptStmt", "classyoi_1_1conceptStmt.html", "classyoi_1_1conceptStmt" ],
      [ "constructorDecl", "classyoi_1_1constructorDecl.html", "classyoi_1_1constructorDecl" ],
      [ "constructorDef", "classyoi_1_1constructorDef.html", "classyoi_1_1constructorDef" ],
      [ "continueStmt", "classyoi_1_1continueStmt.html", null ],
      [ "dataStructDefStmt", "classyoi_1_1dataStructDefStmt.html", "classyoi_1_1dataStructDefStmt" ],
      [ "decltypeExpr", "classyoi_1_1decltypeExpr.html", "classyoi_1_1decltypeExpr" ],
      [ "definitionArguments", "classyoi_1_1definitionArguments.html", "classyoi_1_1definitionArguments" ],
      [ "defTemplateArg", "classyoi_1_1defTemplateArg.html", "classyoi_1_1defTemplateArg" ],
      [ "defTemplateArgSpec", "classyoi_1_1defTemplateArgSpec.html", "classyoi_1_1defTemplateArgSpec" ],
      [ "Diagnostic", "structyoi_1_1Diagnostic.html", "structyoi_1_1Diagnostic" ],
      [ "DiagnosticEngine", "classyoi_1_1DiagnosticEngine.html", "classyoi_1_1DiagnosticEngine" ],
      [ "dynCastExpression", "classyoi_1_1dynCastExpression.html", "classyoi_1_1dynCastExpression" ],
      [ "enum_range", "classyoi_1_1enum__range.html", "classyoi_1_1enum__range" ],
      [ "enumerationDefinition", "classyoi_1_1enumerationDefinition.html", "classyoi_1_1enumerationDefinition" ],
      [ "enumerationPair", "classyoi_1_1enumerationPair.html", "classyoi_1_1enumerationPair" ],
      [ "equalityExpr", "classyoi_1_1equalityExpr.html", "classyoi_1_1equalityExpr" ],
      [ "exclusiveExpr", "classyoi_1_1exclusiveExpr.html", "classyoi_1_1exclusiveExpr" ],
      [ "exportDecl", "classyoi_1_1exportDecl.html", "classyoi_1_1exportDecl" ],
      [ "externModuleAccessExpression", "classyoi_1_1externModuleAccessExpression.html", "classyoi_1_1externModuleAccessExpression" ],
      [ "finalizerDecl", "classyoi_1_1finalizerDecl.html", null ],
      [ "finalizerDef", "classyoi_1_1finalizerDef.html", "classyoi_1_1finalizerDef" ],
      [ "forEachStmt", "classyoi_1_1forEachStmt.html", "classyoi_1_1forEachStmt" ],
      [ "FormatOption", "structyoi_1_1FormatOption.html", "structyoi_1_1FormatOption" ],
      [ "Formatter", "classyoi_1_1Formatter.html", "classyoi_1_1Formatter" ],
      [ "forStmt", "classyoi_1_1forStmt.html", "classyoi_1_1forStmt" ],
      [ "funcDefStmt", "classyoi_1_1funcDefStmt.html", "classyoi_1_1funcDefStmt" ],
      [ "funcExpr", "classyoi_1_1funcExpr.html", "classyoi_1_1funcExpr" ],
      [ "FunctionAnalysisInfo", "structyoi_1_1FunctionAnalysisInfo.html", "structyoi_1_1FunctionAnalysisInfo" ],
      [ "funcTypeSpec", "classyoi_1_1funcTypeSpec.html", "classyoi_1_1funcTypeSpec" ],
      [ "globalStmt", "classyoi_1_1globalStmt.html", "classyoi_1_1globalStmt" ],
      [ "hoshiModule", "classyoi_1_1hoshiModule.html", "classyoi_1_1hoshiModule" ],
      [ "identifier", "classyoi_1_1identifier.html", "classyoi_1_1identifier" ],
      [ "identifierWithDefTemplateArg", "classyoi_1_1identifierWithDefTemplateArg.html", "classyoi_1_1identifierWithDefTemplateArg" ],
      [ "identifierWithTemplateArg", "classyoi_1_1identifierWithTemplateArg.html", "classyoi_1_1identifierWithTemplateArg" ],
      [ "identifierWithTypeSpec", "classyoi_1_1identifierWithTypeSpec.html", "classyoi_1_1identifierWithTypeSpec" ],
      [ "ifStmt", "classyoi_1_1ifStmt.html", "classyoi_1_1ifStmt" ],
      [ "implInner", "classyoi_1_1implInner.html", "classyoi_1_1implInner" ],
      [ "implInnerPair", "classyoi_1_1implInnerPair.html", "classyoi_1_1implInnerPair" ],
      [ "implStmt", "classyoi_1_1implStmt.html", "classyoi_1_1implStmt" ],
      [ "importDecl", "classyoi_1_1importDecl.html", "classyoi_1_1importDecl" ],
      [ "inclusiveExpr", "classyoi_1_1inclusiveExpr.html", "classyoi_1_1inclusiveExpr" ],
      [ "inCodeBlockStmt", "classyoi_1_1inCodeBlockStmt.html", "classyoi_1_1inCodeBlockStmt" ],
      [ "indexPool", "classyoi_1_1indexPool.html", "classyoi_1_1indexPool" ],
      [ "indexTable", "classyoi_1_1indexTable.html", "classyoi_1_1indexTable" ],
      [ "indexTableDeprecated", "classyoi_1_1indexTableDeprecated.html", "classyoi_1_1indexTableDeprecated" ],
      [ "innerMethodDecl", "classyoi_1_1innerMethodDecl.html", "classyoi_1_1innerMethodDecl" ],
      [ "innerMethodDef", "classyoi_1_1innerMethodDef.html", "classyoi_1_1innerMethodDef" ],
      [ "interfaceDefInner", "classyoi_1_1interfaceDefInner.html", "classyoi_1_1interfaceDefInner" ],
      [ "interfaceDefInnerPair", "classyoi_1_1interfaceDefInnerPair.html", "classyoi_1_1interfaceDefInnerPair" ],
      [ "interfaceDefStmt", "classyoi_1_1interfaceDefStmt.html", "classyoi_1_1interfaceDefStmt" ],
      [ "invocationArguments", "classyoi_1_1invocationArguments.html", "classyoi_1_1invocationArguments" ],
      [ "IR", "classyoi_1_1IR.html", "classyoi_1_1IR" ],
      [ "IRBuildConfig", "structyoi_1_1IRBuildConfig.html", "structyoi_1_1IRBuildConfig" ],
      [ "IRBuilder", "classyoi_1_1IRBuilder.html", "classyoi_1_1IRBuilder" ],
      [ "IRCodeBlock", "classyoi_1_1IRCodeBlock.html", "classyoi_1_1IRCodeBlock" ],
      [ "IRConcept", "classyoi_1_1IRConcept.html", "classyoi_1_1IRConcept" ],
      [ "IRDataStructDefinition", "classyoi_1_1IRDataStructDefinition.html", "classyoi_1_1IRDataStructDefinition" ],
      [ "IRDebugInfo", "structyoi_1_1IRDebugInfo.html", "structyoi_1_1IRDebugInfo" ],
      [ "IREnumerationType", "classyoi_1_1IREnumerationType.html", "classyoi_1_1IREnumerationType" ],
      [ "IRExternEntry", "classyoi_1_1IRExternEntry.html", "classyoi_1_1IRExternEntry" ],
      [ "IRFFITable", "classyoi_1_1IRFFITable.html", "classyoi_1_1IRFFITable" ],
      [ "IRFunctionDefinition", "classyoi_1_1IRFunctionDefinition.html", "classyoi_1_1IRFunctionDefinition" ],
      [ "IRFunctionOptimizer", "classyoi_1_1IRFunctionOptimizer.html", "classyoi_1_1IRFunctionOptimizer" ],
      [ "IRFunctionTemplate", "classyoi_1_1IRFunctionTemplate.html", "classyoi_1_1IRFunctionTemplate" ],
      [ "IRInterfaceImplementationDefinition", "classyoi_1_1IRInterfaceImplementationDefinition.html", "classyoi_1_1IRInterfaceImplementationDefinition" ],
      [ "IRInterfaceImplementationTemplate", "classyoi_1_1IRInterfaceImplementationTemplate.html", "classyoi_1_1IRInterfaceImplementationTemplate" ],
      [ "IRInterfaceInstanceDefinition", "classyoi_1_1IRInterfaceInstanceDefinition.html", "classyoi_1_1IRInterfaceInstanceDefinition" ],
      [ "IRInterfaceInstanceTemplate", "classyoi_1_1IRInterfaceInstanceTemplate.html", "classyoi_1_1IRInterfaceInstanceTemplate" ],
      [ "IRLinker", "classyoi_1_1IRLinker.html", "classyoi_1_1IRLinker" ],
      [ "IRMetadata", "structyoi_1_1IRMetadata.html", "structyoi_1_1IRMetadata" ],
      [ "IRModule", "classyoi_1_1IRModule.html", "classyoi_1_1IRModule" ],
      [ "IRObjectFile", "classyoi_1_1IRObjectFile.html", "classyoi_1_1IRObjectFile" ],
      [ "IROperand", "classyoi_1_1IROperand.html", "classyoi_1_1IROperand" ],
      [ "IROptimizer", "classyoi_1_1IROptimizer.html", "classyoi_1_1IROptimizer" ],
      [ "IRStringLiteralPool", "classyoi_1_1IRStringLiteralPool.html", "classyoi_1_1IRStringLiteralPool" ],
      [ "IRStructDefinition", "classyoi_1_1IRStructDefinition.html", "classyoi_1_1IRStructDefinition" ],
      [ "IRStructTemplate", "classyoi_1_1IRStructTemplate.html", "classyoi_1_1IRStructTemplate" ],
      [ "IRTemplateBuilder", "classyoi_1_1IRTemplateBuilder.html", "classyoi_1_1IRTemplateBuilder" ],
      [ "IRTypeAlias", "classyoi_1_1IRTypeAlias.html", "classyoi_1_1IRTypeAlias" ],
      [ "IRValueType", "classyoi_1_1IRValueType.html", "classyoi_1_1IRValueType" ],
      [ "IRVariableTable", "classyoi_1_1IRVariableTable.html", "classyoi_1_1IRVariableTable" ],
      [ "lambdaCapture", "classyoi_1_1lambdaCapture.html", "classyoi_1_1lambdaCapture" ],
      [ "lambdaExpr", "classyoi_1_1lambdaExpr.html", "classyoi_1_1lambdaExpr" ],
      [ "leftExpr", "classyoi_1_1leftExpr.html", "classyoi_1_1leftExpr" ],
      [ "letAssignmentPair", "classyoi_1_1letAssignmentPair.html", "classyoi_1_1letAssignmentPair" ],
      [ "letAssignmentPairLHS", "classyoi_1_1letAssignmentPairLHS.html", "classyoi_1_1letAssignmentPairLHS" ],
      [ "letStmt", "classyoi_1_1letStmt.html", "classyoi_1_1letStmt" ],
      [ "lexer", "classyoi_1_1lexer.html", "classyoi_1_1lexer" ],
      [ "LLVMCodegen", "classyoi_1_1LLVMCodegen.html", "classyoi_1_1LLVMCodegen" ],
      [ "logicalAndExpr", "classyoi_1_1logicalAndExpr.html", "classyoi_1_1logicalAndExpr" ],
      [ "logicalOrExpr", "classyoi_1_1logicalOrExpr.html", "classyoi_1_1logicalOrExpr" ],
      [ "marcoDescriptor", "classyoi_1_1marcoDescriptor.html", "classyoi_1_1marcoDescriptor" ],
      [ "marcoPair", "classyoi_1_1marcoPair.html", "classyoi_1_1marcoPair" ],
      [ "memberExpr", "classyoi_1_1memberExpr.html", "classyoi_1_1memberExpr" ],
      [ "moduleContext", "classyoi_1_1moduleContext.html", "classyoi_1_1moduleContext" ],
      [ "mulExpr", "classyoi_1_1mulExpr.html", "classyoi_1_1mulExpr" ],
      [ "newExpression", "classyoi_1_1newExpression.html", "classyoi_1_1newExpression" ],
      [ "ObjectLinker", "classyoi_1_1ObjectLinker.html", "classyoi_1_1ObjectLinker" ],
      [ "primary", "classyoi_1_1primary.html", "classyoi_1_1primary" ],
      [ "relationalExpr", "classyoi_1_1relationalExpr.html", "classyoi_1_1relationalExpr" ],
      [ "returnStmt", "classyoi_1_1returnStmt.html", "classyoi_1_1returnStmt" ],
      [ "rExpr", "classyoi_1_1rExpr.html", "classyoi_1_1rExpr" ],
      [ "satisfyClause", "classyoi_1_1satisfyClause.html", "classyoi_1_1satisfyClause" ],
      [ "satisfyStmt", "classyoi_1_1satisfyStmt.html", "classyoi_1_1satisfyStmt" ],
      [ "shiftExpr", "classyoi_1_1shiftExpr.html", "classyoi_1_1shiftExpr" ],
      [ "structDefInner", "classyoi_1_1structDefInner.html", "classyoi_1_1structDefInner" ],
      [ "structDefInnerPair", "classyoi_1_1structDefInnerPair.html", "classyoi_1_1structDefInnerPair" ],
      [ "structDefStmt", "classyoi_1_1structDefStmt.html", "classyoi_1_1structDefStmt" ],
      [ "subscript", "classyoi_1_1subscript.html", "classyoi_1_1subscript" ],
      [ "subscriptExpr", "classyoi_1_1subscriptExpr.html", "classyoi_1_1subscriptExpr" ],
      [ "templateArg", "classyoi_1_1templateArg.html", "classyoi_1_1templateArg" ],
      [ "templateArgSpec", "classyoi_1_1templateArgSpec.html", "classyoi_1_1templateArgSpec" ],
      [ "throwStmt", "classyoi_1_1throwStmt.html", "classyoi_1_1throwStmt" ],
      [ "tryCatchStmt", "classyoi_1_1tryCatchStmt.html", "classyoi_1_1tryCatchStmt" ],
      [ "typeAliasStmt", "classyoi_1_1typeAliasStmt.html", "classyoi_1_1typeAliasStmt" ],
      [ "typeIdExpression", "classyoi_1_1typeIdExpression.html", "classyoi_1_1typeIdExpression" ],
      [ "typeSpec", "classyoi_1_1typeSpec.html", "classyoi_1_1typeSpec" ],
      [ "uniqueExpr", "classyoi_1_1uniqueExpr.html", "classyoi_1_1uniqueExpr" ],
      [ "unnamedDefinitionArguments", "classyoi_1_1unnamedDefinitionArguments.html", "classyoi_1_1unnamedDefinitionArguments" ],
      [ "useStmt", "classyoi_1_1useStmt.html", "classyoi_1_1useStmt" ],
      [ "visitor", "classyoi_1_1visitor.html", "classyoi_1_1visitor" ],
      [ "whileStmt", "classyoi_1_1whileStmt.html", "classyoi_1_1whileStmt" ],
      [ "yieldStmt", "classyoi_1_1yieldStmt.html", "classyoi_1_1yieldStmt" ]
    ] ],
    [ "adl_serializer", "structadl__serializer.html", "structadl__serializer" ],
    [ "AllocatedMemoryList", "structAllocatedMemoryList.html", "structAllocatedMemoryList" ],
    [ "basic_json", "classbasic__json.html", "classbasic__json" ],
    [ "byte_container_with_subtype", "classbyte__container__with__subtype.html", "classbyte__container__with__subtype" ],
    [ "HPerfContext", "structHPerfContext.html", "structHPerfContext" ],
    [ "HPerfEvent", "structHPerfEvent.html", "structHPerfEvent" ],
    [ "HPerfEventFuncEnter", "structHPerfEventFuncEnter.html", "structHPerfEventFuncEnter" ],
    [ "HPerfEventFuncLeave", "structHPerfEventFuncLeave.html", "structHPerfEventFuncLeave" ],
    [ "HPerfEventMemAlloc", "structHPerfEventMemAlloc.html", "structHPerfEventMemAlloc" ],
    [ "HPerfEventMemFree", "structHPerfEventMemFree.html", "structHPerfEventMemFree" ],
    [ "HPerfPage", "structHPerfPage.html", "structHPerfPage" ],
    [ "HPerfTimestamp", "structHPerfTimestamp.html", "structHPerfTimestamp" ],
    [ "json_pointer", "classjson__pointer.html", "classjson__pointer" ],
    [ "json_sax", "structjson__sax.html", "structjson__sax" ],
    [ "ordered_map", "structordered__map.html", "structordered__map" ],
    [ "Point", "structPoint.html", "structPoint" ],
    [ "runtime_signal_handler_info", "structruntime__signal__handler__info.html", "structruntime__signal__handler__info" ],
    [ "ThreadStarterArgs", "structThreadStarterArgs.html", "structThreadStarterArgs" ],
    [ "utf8Unicode", "classutf8Unicode.html", "classutf8Unicode" ],
    [ "WeakSlot", "structWeakSlot.html", "structWeakSlot" ],
    [ "YoiBooleanObject", "structYoiBooleanObject.html", "structYoiBooleanObject" ],
    [ "YoiCharObject", "structYoiCharObject.html", "structYoiCharObject" ],
    [ "YoiDecimalObject", "structYoiDecimalObject.html", "structYoiDecimalObject" ],
    [ "YoiIntAndIntObject", "structYoiIntAndIntObject.html", "structYoiIntAndIntObject" ],
    [ "YoiIntegerObject", "structYoiIntegerObject.html", "structYoiIntegerObject" ],
    [ "YoiObject", "structYoiObject.html", "structYoiObject" ],
    [ "YoiObjectArray", "structYoiObjectArray.html", "structYoiObjectArray" ],
    [ "YoiResultUnsignedAndIntObject", "structYoiResultUnsignedAndIntObject.html", "structYoiResultUnsignedAndIntObject" ],
    [ "YoiShortObject", "structYoiShortObject.html", "structYoiShortObject" ],
    [ "YoiStringObject", "structYoiStringObject.html", "structYoiStringObject" ],
    [ "YoiTypeInfo", "structYoiTypeInfo.html", "structYoiTypeInfo" ],
    [ "YoiTypeInfoObject", "structYoiTypeInfoObject.html", "structYoiTypeInfoObject" ],
    [ "YoiUnsignedObject", "structYoiUnsignedObject.html", "structYoiUnsignedObject" ],
    [ "YoiVoidCallableInterface", "structYoiVoidCallableInterface.html", "structYoiVoidCallableInterface" ],
    [ "YoiVoidIntCallableInterface", "structYoiVoidIntCallableInterface.html", "structYoiVoidIntCallableInterface" ]
];