var hierarchy =
[
    [ "AllocatedMemoryList", "structAllocatedMemoryList.html", null ],
    [ "AnalysisState", "structyoi_1_1AnalysisState.html", null ],
    [ "Argument", "structyoi_1_1IRTemplateBuilder_1_1Argument.html", null ],
    [ "AST", "classyoi_1_1AST.html", [
      [ "abstractExpr", "classyoi_1_1abstractExpr.html", null ],
      [ "addExpr", "classyoi_1_1addExpr.html", null ],
      [ "andExpr", "classyoi_1_1andExpr.html", null ],
      [ "basicLiterals", "classyoi_1_1basicLiterals.html", null ],
      [ "breakStmt", "classyoi_1_1breakStmt.html", null ],
      [ "catchParam", "classyoi_1_1catchParam.html", null ],
      [ "codeBlock", "classyoi_1_1codeBlock.html", null ],
      [ "constructorDecl", "classyoi_1_1constructorDecl.html", null ],
      [ "constructorDef", "classyoi_1_1constructorDef.html", null ],
      [ "continueStmt", "classyoi_1_1continueStmt.html", null ],
      [ "defTemplateArg", "classyoi_1_1defTemplateArg.html", null ],
      [ "defTemplateArgSpec", "classyoi_1_1defTemplateArgSpec.html", null ],
      [ "definitionArguments", "classyoi_1_1definitionArguments.html", null ],
      [ "dynCastExpression", "classyoi_1_1dynCastExpression.html", null ],
      [ "enumerationDefinition", "classyoi_1_1enumerationDefinition.html", null ],
      [ "equalityExpr", "classyoi_1_1equalityExpr.html", null ],
      [ "exclusiveExpr", "classyoi_1_1exclusiveExpr.html", null ],
      [ "exportDecl", "classyoi_1_1exportDecl.html", null ],
      [ "externModuleAccessExpression", "classyoi_1_1externModuleAccessExpression.html", null ],
      [ "finalizerDecl", "classyoi_1_1finalizerDecl.html", null ],
      [ "finalizerDef", "classyoi_1_1finalizerDef.html", null ],
      [ "forEachStmt", "classyoi_1_1forEachStmt.html", null ],
      [ "forStmt", "classyoi_1_1forStmt.html", null ],
      [ "funcDefStmt", "classyoi_1_1funcDefStmt.html", null ],
      [ "funcExpr", "classyoi_1_1funcExpr.html", null ],
      [ "funcTypeSpec", "classyoi_1_1funcTypeSpec.html", null ],
      [ "globalStmt", "classyoi_1_1globalStmt.html", null ],
      [ "hoshiModule", "classyoi_1_1hoshiModule.html", null ],
      [ "identifier", "classyoi_1_1identifier.html", null ],
      [ "identifierWithDefTemplateArg", "classyoi_1_1identifierWithDefTemplateArg.html", null ],
      [ "identifierWithTemplateArg", "classyoi_1_1identifierWithTemplateArg.html", null ],
      [ "identifierWithTypeSpec", "classyoi_1_1identifierWithTypeSpec.html", null ],
      [ "ifStmt", "classyoi_1_1ifStmt.html", null ],
      [ "implInner", "classyoi_1_1implInner.html", null ],
      [ "implInnerPair", "classyoi_1_1implInnerPair.html", null ],
      [ "implStmt", "classyoi_1_1implStmt.html", null ],
      [ "importDecl", "classyoi_1_1importDecl.html", null ],
      [ "inCodeBlockStmt", "classyoi_1_1inCodeBlockStmt.html", null ],
      [ "inclusiveExpr", "classyoi_1_1inclusiveExpr.html", null ],
      [ "innerMethodDecl", "classyoi_1_1innerMethodDecl.html", null ],
      [ "innerMethodDef", "classyoi_1_1innerMethodDef.html", null ],
      [ "interfaceDefInner", "classyoi_1_1interfaceDefInner.html", null ],
      [ "interfaceDefInnerPair", "classyoi_1_1interfaceDefInnerPair.html", null ],
      [ "interfaceDefStmt", "classyoi_1_1interfaceDefStmt.html", null ],
      [ "invocationArguments", "classyoi_1_1invocationArguments.html", null ],
      [ "lambdaExpr", "classyoi_1_1lambdaExpr.html", null ],
      [ "leftExpr", "classyoi_1_1leftExpr.html", null ],
      [ "letAssignmentPair", "classyoi_1_1letAssignmentPair.html", null ],
      [ "letAssignmentPairLHS", "classyoi_1_1letAssignmentPairLHS.html", null ],
      [ "letStmt", "classyoi_1_1letStmt.html", null ],
      [ "logicalAndExpr", "classyoi_1_1logicalAndExpr.html", null ],
      [ "logicalOrExpr", "classyoi_1_1logicalOrExpr.html", null ],
      [ "marcoDescriptor", "classyoi_1_1marcoDescriptor.html", null ],
      [ "marcoPair", "classyoi_1_1marcoPair.html", null ],
      [ "memberExpr", "classyoi_1_1memberExpr.html", null ],
      [ "mulExpr", "classyoi_1_1mulExpr.html", null ],
      [ "newExpression", "classyoi_1_1newExpression.html", null ],
      [ "primary", "classyoi_1_1primary.html", null ],
      [ "rExpr", "classyoi_1_1rExpr.html", null ],
      [ "relationalExpr", "classyoi_1_1relationalExpr.html", null ],
      [ "returnStmt", "classyoi_1_1returnStmt.html", null ],
      [ "shiftExpr", "classyoi_1_1shiftExpr.html", null ],
      [ "structDefInner", "classyoi_1_1structDefInner.html", null ],
      [ "structDefInnerPair", "classyoi_1_1structDefInnerPair.html", null ],
      [ "structDefStmt", "classyoi_1_1structDefStmt.html", null ],
      [ "subscript", "classyoi_1_1subscript.html", null ],
      [ "subscriptExpr", "classyoi_1_1subscriptExpr.html", null ],
      [ "templateArg", "classyoi_1_1templateArg.html", null ],
      [ "templateArgSpec", "classyoi_1_1templateArgSpec.html", null ],
      [ "throwStmt", "classyoi_1_1throwStmt.html", null ],
      [ "tryCatchStmt", "classyoi_1_1tryCatchStmt.html", null ],
      [ "typeAliasStmt", "classyoi_1_1typeAliasStmt.html", null ],
      [ "typeIdExpression", "classyoi_1_1typeIdExpression.html", null ],
      [ "typeSpec", "classyoi_1_1typeSpec.html", null ],
      [ "uniqueExpr", "classyoi_1_1uniqueExpr.html", null ],
      [ "unnamedDefinitionArguments", "classyoi_1_1unnamedDefinitionArguments.html", null ],
      [ "useStmt", "classyoi_1_1useStmt.html", null ],
      [ "whileStmt", "classyoi_1_1whileStmt.html", null ]
    ] ],
    [ "bool_constant", null, [
      [ "has_is_flags< T, std::void_t< decltype(customize::enum_range< T >::is_flags)> >", "structmagic__enum_1_1detail_1_1has__is__flags_3_01T_00_01std_1_1void__t_3_01decltype_07customize13d690b0add06bd55a4dd8d99f1b8c51.html", null ],
      [ "is_reflected< E, S >", "structmagic__enum_1_1detail_1_1is__reflected.html", null ],
      [ "is_scoped_enum< T, true >", "structmagic__enum_1_1detail_1_1is__scoped__enum_3_01T_00_01true_01_4.html", null ],
      [ "is_unscoped_enum< T, true >", "structmagic__enum_1_1detail_1_1is__unscoped__enum_3_01T_00_01true_01_4.html", null ]
    ] ],
    [ "Builder", "structyoi_1_1IRBuildConfig_1_1Builder.html", null ],
    [ "Builder", "classyoi_1_1IREnumerationType_1_1Builder.html", null ],
    [ "Builder", "structyoi_1_1IRFunctionDefinition_1_1Builder.html", null ],
    [ "Builder", "structyoi_1_1IRInterfaceImplementationDefinition_1_1Builder.html", null ],
    [ "Builder", "structyoi_1_1IRInterfaceInstanceDefinition_1_1Builder.html", null ],
    [ "Builder", "structyoi_1_1IRStructDefinition_1_1Builder.html", null ],
    [ "BuiltinModuleBuilder", "classyoi_1_1BuiltinModuleBuilder.html", null ],
    [ "CallGraph", "structyoi_1_1CallGraph.html", null ],
    [ "case_insensitive< Op >", "classmagic__enum_1_1detail_1_1case__insensitive.html", null ],
    [ "ContributedInstructionSet", "structyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item_1_1ContributedInstructionSet.html", null ],
    [ "ControlFlowAnalysis", "structyoi_1_1LLVMCodegen_1_1ControlFlowAnalysis.html", null ],
    [ "enable_if_enum< bool, R >", "structmagic__enum_1_1detail_1_1enable__if__enum.html", null ],
    [ "enable_if_enum< true, R >", "structmagic__enum_1_1detail_1_1enable__if__enum_3_01true_00_01R_01_4.html", null ],
    [ "enable_shared_from_this", null, [
      [ "IRModule", "classyoi_1_1IRModule.html", null ],
      [ "compilerContext", "classyoi_1_1compilerContext.html", null ]
    ] ],
    [ "enum_range< E >", "structmagic__enum_1_1customize_1_1enum__range.html", null ],
    [ "enum_range< enumT, TSize >", "classyoi_1_1enum__range.html", null ],
    [ "enum_range< Opcode >", "classyoi_1_1enum__range.html", null ],
    [ "enum_range< operandType >", "classyoi_1_1enum__range.html", null ],
    [ "false_type", null, [
      [ "has_is_flags< T, typename >", "structmagic__enum_1_1detail_1_1has__is__flags.html", null ],
      [ "is_scoped_enum< T, bool >", "structmagic__enum_1_1detail_1_1is__scoped__enum.html", [
        [ "is_scoped_enum< T >", "structmagic__enum_1_1is__scoped__enum.html", null ]
      ] ],
      [ "is_unscoped_enum< T, bool >", "structmagic__enum_1_1detail_1_1is__unscoped__enum.html", [
        [ "is_unscoped_enum< T >", "structmagic__enum_1_1is__unscoped__enum.html", null ]
      ] ],
      [ "supported< T >", "structmagic__enum_1_1detail_1_1supported.html", null ]
    ] ],
    [ "FunctionAnalysisInfo", "structyoi_1_1FunctionAnalysisInfo.html", null ],
    [ "ifBlock", "structyoi_1_1ifStmt_1_1ifBlock.html", null ],
    [ "ImportLibrary", "classyoi_1_1IRFFITable_1_1ImportLibrary.html", null ],
    [ "indexPool< T >", "classyoi_1_1indexPool.html", null ],
    [ "indexPool< yoi::wstr >", "classyoi_1_1indexPool.html", null ],
    [ "indexTable< A, B >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IREnumerationType > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRExternEntry > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRFunctionDefinition > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRFunctionTemplate > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRInterfaceImplementationDefinition > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRInterfaceInstanceDefinition > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRStructDefinition > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::IRValueType > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::shared_ptr< yoi::moduleContext > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, std::tuple< yoi::indexT, yoi::indexT, yoi::vec< IRFunctionDefinition::FunctionAttrs > > >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, yoi::indexT >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, yoi::IRFFITable::ImportLibrary >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, yoi::IRTemplateBuilder::Argument >", "classyoi_1_1indexTable.html", null ],
    [ "indexTable< yoi::wstr, yoi::symbol >", "classyoi_1_1indexTable.html", null ],
    [ "indexTableDeprecated< A, B >", "classyoi_1_1indexTableDeprecated.html", null ],
    [ "integral_constant", null, [
      [ "range_max< T, typename >", "structmagic__enum_1_1detail_1_1range__max.html", null ],
      [ "range_max< T, std::void_t< decltype(customize::enum_range< T >::max)> >", "structmagic__enum_1_1detail_1_1range__max_3_01T_00_01std_1_1void__t_3_01decltype_07customize_1_1376f6eb50191a2e253cb2b0e1d2386a7.html", null ],
      [ "range_min< T, typename >", "structmagic__enum_1_1detail_1_1range__min.html", null ],
      [ "range_min< T, std::void_t< decltype(customize::enum_range< T >::min)> >", "structmagic__enum_1_1detail_1_1range__min_3_01T_00_01std_1_1void__t_3_01decltype_07customize_1_14afc0df766d6bd32918519501ffe6473.html", null ]
    ] ],
    [ "IR", "classyoi_1_1IR.html", null ],
    [ "IRBuildConfig", "structyoi_1_1IRBuildConfig.html", null ],
    [ "IRBuilder", "classyoi_1_1IRBuilder.html", null ],
    [ "IRCodeBlock", "classyoi_1_1IRCodeBlock.html", null ],
    [ "IRDebugInfo", "structyoi_1_1IRDebugInfo.html", null ],
    [ "IREnumerationType", "classyoi_1_1IREnumerationType.html", null ],
    [ "IRExternEntry", "classyoi_1_1IRExternEntry.html", null ],
    [ "IRFFITable", "classyoi_1_1IRFFITable.html", null ],
    [ "IRFunctionDefinition", "classyoi_1_1IRFunctionDefinition.html", null ],
    [ "IRFunctionOptimizer", "classyoi_1_1IRFunctionOptimizer.html", null ],
    [ "IRFunctionTemplate", "classyoi_1_1IRFunctionTemplate.html", null ],
    [ "IRInterfaceImplementationDefinition", "classyoi_1_1IRInterfaceImplementationDefinition.html", null ],
    [ "IRInterfaceImplementationTemplate", "classyoi_1_1IRInterfaceImplementationTemplate.html", null ],
    [ "IRInterfaceInstanceDefinition", "classyoi_1_1IRInterfaceInstanceDefinition.html", null ],
    [ "IRInterfaceInstanceTemplate", "classyoi_1_1IRInterfaceInstanceTemplate.html", null ],
    [ "IRLinker", "classyoi_1_1IRLinker.html", null ],
    [ "IRMetadata", "structyoi_1_1IRMetadata.html", null ],
    [ "IRObjectFile", "classyoi_1_1IRObjectFile.html", null ],
    [ "IROperand", "classyoi_1_1IROperand.html", null ],
    [ "IROptimizer", "classyoi_1_1IROptimizer.html", null ],
    [ "IRStringLiteralPool", "classyoi_1_1IRStringLiteralPool.html", null ],
    [ "IRStructDefinition", "classyoi_1_1IRStructDefinition.html", null ],
    [ "IRStructTemplate", "classyoi_1_1IRStructTemplate.html", null ],
    [ "IRTemplateBuilder", "classyoi_1_1IRTemplateBuilder.html", [
      [ "Builder", "classyoi_1_1IRFunctionTemplate_1_1Builder.html", null ],
      [ "Builder", "classyoi_1_1IRInterfaceImplementationTemplate_1_1Builder.html", null ],
      [ "Builder", "classyoi_1_1IRInterfaceInstanceTemplate_1_1Builder.html", null ],
      [ "Builder", "classyoi_1_1IRStructTemplate_1_1Builder.html", null ]
    ] ],
    [ "IRTypeAlias", "classyoi_1_1IRTypeAlias.html", null ],
    [ "IRValueType", "classyoi_1_1IRValueType.html", null ],
    [ "IRVariableTable", "classyoi_1_1IRVariableTable.html", null ],
    [ "Item", "structyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item.html", null ],
    [ "iterator", "classyoi_1_1enum__range_1_1iterator.html", null ],
    [ "iterator", "classyoi_1_1indexTable_1_1iterator.html", null ],
    [ "iterator", "classyoi_1_1indexTableDeprecated_1_1iterator.html", null ],
    [ "Iterator", "structyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item_1_1ContributedInstructionSet_1_1Iterator.html", null ],
    [ "lexer", "classyoi_1_1lexer.html", null ],
    [ "lexerState", "structyoi_1_1lexer_1_1lexerState.html", null ],
    [ "LLVMCodegen", "classyoi_1_1LLVMCodegen.html", null ],
    [ "LoopContext", "structyoi_1_1IRBuilder_1_1LoopContext.html", null ],
    [ "moduleContext", "classyoi_1_1moduleContext.html", null ],
    [ "nameInfo", "structyoi_1_1IRStructDefinition_1_1nameInfo.html", null ],
    [ "ObjectLinker", "classyoi_1_1ObjectLinker.html", [
      [ "ccObjectLinker", "classyoi_1_1ccObjectLinker.html", null ],
      [ "clObjectLinker", "classyoi_1_1clObjectLinker.html", null ]
    ] ],
    [ "operandValue", "unionyoi_1_1IROperand_1_1operandValue.html", null ],
    [ "OverloadResult", "structyoi_1_1visitor_1_1OverloadResult.html", null ],
    [ "pair", null, [
      [ "customize_t", "classmagic__enum_1_1customize_1_1customize__t.html", null ]
    ] ],
    [ "PossibleValue", "unionyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item_1_1PossibleValue.html", null ],
    [ "SimulationStack", "structyoi_1_1IRFunctionOptimizer_1_1SimulationStack.html", null ],
    [ "StackValue", "structyoi_1_1LLVMCodegen_1_1StackValue.html", null ],
    [ "static_str< N >", "classmagic__enum_1_1detail_1_1static__str.html", null ],
    [ "static_str< 0 >", "classmagic__enum_1_1detail_1_1static__str_3_010_01_4.html", null ],
    [ "str_view", "structmagic__enum_1_1detail_1_1str__view.html", null ],
    [ "symbol", "classyoi_1_1symbol.html", null ],
    [ "symbolTable", "classyoi_1_1symbolTable.html", null ],
    [ "ThreadStarterArgs", "structThreadStarterArgs.html", null ],
    [ "token", "structyoi_1_1lexer_1_1token.html", null ],
    [ "underlying_type< T, bool >", "structmagic__enum_1_1detail_1_1underlying__type.html", [
      [ "underlying_type< T >", "structmagic__enum_1_1underlying__type.html", null ]
    ] ],
    [ "underlying_type", null, [
      [ "underlying_type< T, true >", "structmagic__enum_1_1detail_1_1underlying__type_3_01T_00_01true_01_4.html", null ]
    ] ],
    [ "utf8Unicode", "classutf8Unicode.html", null ],
    [ "valid_count_t< N >", "structmagic__enum_1_1detail_1_1valid__count__t.html", null ],
    [ "ValueStackWithPhi", "structyoi_1_1LLVMCodegen_1_1ValueStackWithPhi.html", null ],
    [ "VariablesExtraInfo", "structyoi_1_1IRFunctionOptimizer_1_1VariablesExtraInfo.html", null ],
    [ "vBasicValue", "unionyoi_1_1lexer_1_1token_1_1vBasicValue.html", null ],
    [ "visitor", "classyoi_1_1visitor.html", null ],
    [ "vValue", "unionyoi_1_1globalStmt_1_1vValue.html", null ],
    [ "vValue", "unionyoi_1_1inCodeBlockStmt_1_1vValue.html", null ],
    [ "YoiBooleanObject", "structYoiBooleanObject.html", null ],
    [ "YoiCharObject", "structYoiCharObject.html", null ],
    [ "YoiDecimalObject", "structYoiDecimalObject.html", null ],
    [ "YoiIntegerObject", "structYoiIntegerObject.html", null ],
    [ "YoiObject", "structYoiObject.html", null ],
    [ "YoiObjectArray", "structYoiObjectArray.html", null ],
    [ "YoiResultUnsignedAndIntObject", "structYoiResultUnsignedAndIntObject.html", null ],
    [ "YoiStringObject", "structYoiStringObject.html", null ],
    [ "YoiTypeInfo", "structYoiTypeInfo.html", null ],
    [ "YoiTypeInfoObject", "structYoiTypeInfoObject.html", null ],
    [ "YoiUnsignedObject", "structYoiUnsignedObject.html", null ],
    [ "YoiVoidCallableInterface", "structYoiVoidCallableInterface.html", null ]
];