var IR_8h =
[
    [ "IRBuildConfig", "structyoi_1_1IRBuildConfig.html", "structyoi_1_1IRBuildConfig" ],
    [ "Builder", "structyoi_1_1IRBuildConfig_1_1Builder.html", "structyoi_1_1IRBuildConfig_1_1Builder" ],
    [ "IRDebugInfo", "structyoi_1_1IRDebugInfo.html", "structyoi_1_1IRDebugInfo" ],
    [ "IRValueType", "classyoi_1_1IRValueType.html", "classyoi_1_1IRValueType" ],
    [ "IROperand", "classyoi_1_1IROperand.html", "classyoi_1_1IROperand" ],
    [ "operandValue", "unionyoi_1_1IROperand_1_1operandValue.html", "unionyoi_1_1IROperand_1_1operandValue" ],
    [ "IR", "classyoi_1_1IR.html", "classyoi_1_1IR" ],
    [ "IRCodeBlock", "classyoi_1_1IRCodeBlock.html", "classyoi_1_1IRCodeBlock" ],
    [ "IRVariableTable", "classyoi_1_1IRVariableTable.html", "classyoi_1_1IRVariableTable" ],
    [ "IRFunctionDefinition", "classyoi_1_1IRFunctionDefinition.html", "classyoi_1_1IRFunctionDefinition" ],
    [ "Builder", "structyoi_1_1IRFunctionDefinition_1_1Builder.html", "structyoi_1_1IRFunctionDefinition_1_1Builder" ],
    [ "IRTemplateBuilder", "classyoi_1_1IRTemplateBuilder.html", "classyoi_1_1IRTemplateBuilder" ],
    [ "Argument", "structyoi_1_1IRTemplateBuilder_1_1Argument.html", "structyoi_1_1IRTemplateBuilder_1_1Argument" ],
    [ "IRFunctionTemplate", "classyoi_1_1IRFunctionTemplate.html", "classyoi_1_1IRFunctionTemplate" ],
    [ "Builder", "classyoi_1_1IRFunctionTemplate_1_1Builder.html", "classyoi_1_1IRFunctionTemplate_1_1Builder" ],
    [ "IRStructDefinition", "classyoi_1_1IRStructDefinition.html", "classyoi_1_1IRStructDefinition" ],
    [ "nameInfo", "structyoi_1_1IRStructDefinition_1_1nameInfo.html", "structyoi_1_1IRStructDefinition_1_1nameInfo" ],
    [ "Builder", "structyoi_1_1IRStructDefinition_1_1Builder.html", "structyoi_1_1IRStructDefinition_1_1Builder" ],
    [ "IRStructTemplate", "classyoi_1_1IRStructTemplate.html", "classyoi_1_1IRStructTemplate" ],
    [ "Builder", "classyoi_1_1IRStructTemplate_1_1Builder.html", "classyoi_1_1IRStructTemplate_1_1Builder" ],
    [ "IRInterfaceImplementationDefinition", "classyoi_1_1IRInterfaceImplementationDefinition.html", "classyoi_1_1IRInterfaceImplementationDefinition" ],
    [ "Builder", "structyoi_1_1IRInterfaceImplementationDefinition_1_1Builder.html", "structyoi_1_1IRInterfaceImplementationDefinition_1_1Builder" ],
    [ "IRInterfaceInstanceDefinition", "classyoi_1_1IRInterfaceInstanceDefinition.html", "classyoi_1_1IRInterfaceInstanceDefinition" ],
    [ "Builder", "structyoi_1_1IRInterfaceInstanceDefinition_1_1Builder.html", "structyoi_1_1IRInterfaceInstanceDefinition_1_1Builder" ],
    [ "IRInterfaceInstanceTemplate", "classyoi_1_1IRInterfaceInstanceTemplate.html", "classyoi_1_1IRInterfaceInstanceTemplate" ],
    [ "Builder", "classyoi_1_1IRInterfaceInstanceTemplate_1_1Builder.html", "classyoi_1_1IRInterfaceInstanceTemplate_1_1Builder" ],
    [ "IRInterfaceImplementationTemplate", "classyoi_1_1IRInterfaceImplementationTemplate.html", "classyoi_1_1IRInterfaceImplementationTemplate" ],
    [ "Builder", "classyoi_1_1IRInterfaceImplementationTemplate_1_1Builder.html", "classyoi_1_1IRInterfaceImplementationTemplate_1_1Builder" ],
    [ "IRStringLiteralPool", "classyoi_1_1IRStringLiteralPool.html", "classyoi_1_1IRStringLiteralPool" ],
    [ "IRExternEntry", "classyoi_1_1IRExternEntry.html", "classyoi_1_1IRExternEntry" ],
    [ "IRModule", "classyoi_1_1IRModule.html", "classyoi_1_1IRModule" ],
    [ "IRBuilder", "classyoi_1_1IRBuilder.html", "classyoi_1_1IRBuilder" ],
    [ "IRObjectFile", "classyoi_1_1IRObjectFile.html", "classyoi_1_1IRObjectFile" ],
    [ "IRFFITable", "classyoi_1_1IRFFITable.html", "classyoi_1_1IRFFITable" ],
    [ "ImportLibrary", "classyoi_1_1IRFFITable_1_1ImportLibrary.html", "classyoi_1_1IRFFITable_1_1ImportLibrary" ]
];