# Grammar Basics & Literals
identifier ::= TOK_identifier
basicLiterals ::= TOK_integer | TOK_decimal | TOK_char | TOK_string | TOK_boolean | "null" | TOK_unsignedInt | TOK_shortInt

# Type System
typeSpec ::= typeIdPrefix [ arraySpec ]
           | funcTypeSpec [ arraySpec ]
           | "null"
           | "..." typeSpec

typeIdPrefix ::= externModuleAccessExpression
arraySpec ::= "[" [ { TOK_integer "," } TOK_integer ] "]"
            | "[" "]"

unnamedDefinitionArguments ::= "(" [ { typeSpec "," } typeSpec ] ")"
funcTypeSpec ::= "func" unnamedDefinitionArguments ":" typeSpec

identifierWithTypeSpec ::= identifier ":" typeSpec

# Expressions
templateArgSpec ::= typeSpec
templateArg ::= "<" [ { templateArgSpec "," } templateArgSpec ] ">"

defTemplateArgSpec ::= identifier [ "impl" externModuleAccessExpression ]
defTemplateArg ::= "<" [ { defTemplateArgSpec "," } defTemplateArgSpec ] ">"

identifierWithTemplateArg ::= identifier [ templateArg ]
identifierWithDefTemplateArg ::= identifier [ defTemplateArg ]

externModuleAccessExpression ::= { identifier "." } identifierWithTemplateArg

subscript ::= "[" rExpr "]"
            | invocationArguments

invocationArguments ::= "(" [ { rExpr "," } rExpr ] ")"

subscriptExpr ::= identifierWithTemplateArg { subscript }
memberExpr ::= subscriptExpr { "." subscriptExpr }

bracedInitalizerList ::= "{" [ { rExpr "," } rExpr ] "}"

typeIdExpression ::= "type_id" "<" typeSpec ">"
                  | "type_id" "(" rExpr ")"

dynCastExpression ::= "dyn_cast" "<" typeSpec ">" "(" rExpr ")"

lambdaExpr ::= "func" "[" [ { identifier "," } identifier ] "]" definitionArguments ":" typeSpec codeBlock

funcExpr ::= "func" externModuleAccessExpression [ unnamedDefinitionArguments ]

newExpression ::= "new" externModuleAccessExpression [ "[" rExpr "]" | "[" "]" ] invocationArguments

primary ::= memberExpr 
          | basicLiterals 
          | typeIdExpression 
          | dynCastExpression 
          | newExpression 
          | lambdaExpr 
          | funcExpr 
          | bracedInitalizerList 
          | "(" rExpr ")"

abstractExpr ::= primary [ ( "interfaceof" | "impl" | "as" ) externModuleAccessExpression ]

uniqueExpr ::= [ "++" | "--" | "-" | "!" | "~" ] abstractExpr
leftExpr ::= uniqueExpr [ ( "=" | "+=" | "-=" | "*=" | "/=" | "%=" | ":=" ) rExpr ]

mulExpr ::= leftExpr { ( "*" | "/" | "%" ) leftExpr }
addExpr ::= mulExpr { ( "+" | "-" ) mulExpr }
shiftExpr ::= addExpr { ( "<<" | ">>" ) addExpr }
relationalExpr ::= shiftExpr { ( "<" | ">" | "<=" | ">=" ) shiftExpr }
equalityExpr ::= relationalExpr { ( "==" | "!=" ) relationalExpr }
andExpr ::= equalityExpr { "&" equalityExpr }
exclusiveExpr ::= andExpr { "^" andExpr }
inclusiveExpr ::= exclusiveExpr { "|" exclusiveExpr }
logicalAndExpr ::= inclusiveExpr { "&&" inclusiveExpr }
logicalOrExpr ::= logicalAndExpr { "||" logicalAndExpr }

rExpr ::= logicalOrExpr

# Statements
codeBlock ::= "{" { inCodeBlockStmt } "}"

ifBlock ::= "(" rExpr ")" codeBlock
ifStmt ::= "if" ifBlock { "elif" ifBlock } [ "else" codeBlock ]

whileStmt ::= "while" "(" rExpr ")" codeBlock

forStmt ::= "for" "(" inCodeBlockStmt ";" rExpr ";" inCodeBlockStmt ")" codeBlock

forEachStmt ::= "forEach" "(" identifier ":" rExpr ")" codeBlock

returnStmt ::= "return" [ rExpr ]

breakStmt ::= "break"
continueStmt ::= "continue"

throwStmt ::= "throw" rExpr

catchParam ::= "catch" "(" identifier ":" typeSpec ")" codeBlock
tryCatchStmt ::= "try" codeBlock { catchParam } [ "finally" codeBlock ]

letAssignmentPairLHS ::= identifier
                       | "[" [ { ( identifier | "..." ) "," } ( identifier | "..." ) ] "]"
letAssignmentPair ::= letAssignmentPairLHS [ ":" typeSpec ] "=" rExpr
letStmt ::= "let" letAssignmentPair { "," letAssignmentPair }

inCodeBlockStmt ::= [ marcoDescriptor ] 
                    ( letStmt 
                    | ifStmt 
                    | breakStmt 
                    | continueStmt 
                    | returnStmt 
                    | forEachStmt 
                    | whileStmt 
                    | forStmt 
                    | tryCatchStmt 
                    | throwStmt 
                    | codeBlock 
                    | rExpr
                    )

# Global Definitions
marcoPair ::= identifier ( "==" | "!=" | "<" | ">" | "<=" | ">=" ) ( identifier | TOK_integer | TOK_decimal | TOK_string )
marcoDescriptor ::= "[[" { marcoPair } "]]"

useStmt ::= "use" identifier TOK_string

definitionArguments ::= "(" [ { identifierWithTypeSpec "," } identifierWithTypeSpec ] ")"

funcAttribute ::= "no_ffi" | "no_gc" | "always_inline"

funcDefStmt ::= "func" { funcAttribute } identifierWithDefTemplateArg definitionArguments ":" typeSpec codeBlock

innerMethodDecl ::= { funcAttribute } identifierWithDefTemplateArg definitionArguments ":" typeSpec
innerMethodDef ::= { funcAttribute } identifierWithDefTemplateArg definitionArguments ":" typeSpec codeBlock

constructorDecl ::= "constructor" [ defTemplateArg ] definitionArguments
constructorDef ::= "constructor" [ templateArg ] definitionArguments codeBlock

finalizerDecl ::= "finalizer" "(" ")"
finalizerDef ::= "finalizer" "(" ")" codeBlock

interfaceDefInnerPair ::= identifierWithTypeSpec
                        | innerMethodDecl
interfaceDefInner ::= "{" [ interfaceDefInnerPair { "," interfaceDefInnerPair } ] "}"
interfaceDefStmt ::= "interface" identifierWithDefTemplateArg interfaceDefInner

structDefInnerPair ::= [ "datafield" ] ( identifierWithTypeSpec | innerMethodDecl | constructorDecl | finalizerDecl )
structDefInner ::= "{" [ structDefInnerPair { "," structDefInnerPair } ] "}"
structDefStmt ::= "struct" identifierWithDefTemplateArg structDefInner

dataStructDefStmt ::= "datastruct" identifier structDefInner

implInnerPair ::= innerMethodDef | constructorDef | finalizerDef
implInner ::= "{" [ implInnerPair { "," implInnerPair } ] "}"
implStmt ::= "impl" externModuleAccessExpression [ ":" externModuleAccessExpression ] [ implInner ]

typeAliasStmt ::= "alias" identifierWithDefTemplateArg "=" typeSpec

enumerationPair ::= identifier [ "=" [ "-" ] TOK_integer ]
enumerationDefinition ::= "enum" identifier "{" [ { enumerationPair "," } enumerationPair ] "}"

exportDecl ::= "export" { funcAttribute } typeSpec "as" identifier
importDecl ::= "import" innerMethodDecl "from" TOK_string

globalStmt ::= [ marcoDescriptor ] 
               ( useStmt 
               | interfaceDefStmt 
               | structDefStmt 
               | dataStructDefStmt 
               | implStmt 
               | letStmt 
               | funcDefStmt 
               | exportDecl 
               | importDecl 
               | typeAliasStmt 
               | enumerationDefinition 
               )

hoshiModule ::= { globalStmt }