var searchData=
[
  ['identifier_0',['identifier',['../classyoi_1_1identifier.html',1,'yoi']]],
  ['identifierwithdeftemplatearg_1',['identifierWithDefTemplateArg',['../classyoi_1_1identifierWithDefTemplateArg.html',1,'yoi']]],
  ['identifierwithtemplatearg_2',['identifierWithTemplateArg',['../classyoi_1_1identifierWithTemplateArg.html',1,'yoi']]],
  ['identifierwithtypespec_3',['identifierWithTypeSpec',['../classyoi_1_1identifierWithTypeSpec.html',1,'yoi']]],
  ['ifblock_4',['ifBlock',['../structyoi_1_1ifStmt_1_1ifBlock.html',1,'yoi::ifStmt']]],
  ['ifstmt_5',['ifStmt',['../classyoi_1_1ifStmt.html',1,'yoi']]],
  ['implinner_6',['implInner',['../classyoi_1_1implInner.html',1,'yoi']]],
  ['implinnerpair_7',['implInnerPair',['../classyoi_1_1implInnerPair.html',1,'yoi']]],
  ['implstmt_8',['implStmt',['../classyoi_1_1implStmt.html',1,'yoi']]],
  ['importdecl_9',['importDecl',['../classyoi_1_1importDecl.html',1,'yoi']]],
  ['importlibrary_10',['ImportLibrary',['../classyoi_1_1IRFFITable_1_1ImportLibrary.html',1,'yoi::IRFFITable']]],
  ['inclusiveexpr_11',['inclusiveExpr',['../classyoi_1_1inclusiveExpr.html',1,'yoi']]],
  ['incodeblockstmt_12',['inCodeBlockStmt',['../classyoi_1_1inCodeBlockStmt.html',1,'yoi']]],
  ['indexpool_13',['indexPool',['../classyoi_1_1indexPool.html',1,'yoi']]],
  ['indexpool_3c_20yoi_3a_3awstr_20_3e_14',['indexPool&lt; yoi::wstr &gt;',['../classyoi_1_1indexPool.html',1,'yoi']]],
  ['indextable_15',['indexTable',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airenumerationtype_20_3e_20_3e_16',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IREnumerationType &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airexternentry_20_3e_20_3e_17',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRExternEntry &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airfunctiondefinition_20_3e_20_3e_18',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRFunctionDefinition &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airfunctiontemplate_20_3e_20_3e_19',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRFunctionTemplate &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airinterfaceimplementationdefinition_20_3e_20_3e_20',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRInterfaceImplementationDefinition &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airinterfaceinstancedefinition_20_3e_20_3e_21',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRInterfaceInstanceDefinition &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airstructdefinition_20_3e_20_3e_22',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRStructDefinition &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3airvaluetype_20_3e_20_3e_23',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::IRValueType &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3ashared_5fptr_3c_20yoi_3a_3amodulecontext_20_3e_20_3e_24',['indexTable&lt; yoi::wstr, std::shared_ptr&lt; yoi::moduleContext &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20std_3a_3atuple_3c_20yoi_3a_3aindext_2c_20yoi_3a_3aindext_2c_20yoi_3a_3avec_3c_20irfunctiondefinition_3a_3afunctionattrs_20_3e_20_3e_20_3e_25',['indexTable&lt; yoi::wstr, std::tuple&lt; yoi::indexT, yoi::indexT, yoi::vec&lt; IRFunctionDefinition::FunctionAttrs &gt; &gt; &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20yoi_3a_3aindext_20_3e_26',['indexTable&lt; yoi::wstr, yoi::indexT &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20yoi_3a_3airffitable_3a_3aimportlibrary_20_3e_27',['indexTable&lt; yoi::wstr, yoi::IRFFITable::ImportLibrary &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20yoi_3a_3airtemplatebuilder_3a_3aargument_20_3e_28',['indexTable&lt; yoi::wstr, yoi::IRTemplateBuilder::Argument &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextable_3c_20yoi_3a_3awstr_2c_20yoi_3a_3asymbol_20_3e_29',['indexTable&lt; yoi::wstr, yoi::symbol &gt;',['../classyoi_1_1indexTable.html',1,'yoi']]],
  ['indextabledeprecated_30',['indexTableDeprecated',['../classyoi_1_1indexTableDeprecated.html',1,'yoi']]],
  ['innermethoddecl_31',['innerMethodDecl',['../classyoi_1_1innerMethodDecl.html',1,'yoi']]],
  ['innermethoddef_32',['innerMethodDef',['../classyoi_1_1innerMethodDef.html',1,'yoi']]],
  ['interfacedefinner_33',['interfaceDefInner',['../classyoi_1_1interfaceDefInner.html',1,'yoi']]],
  ['interfacedefinnerpair_34',['interfaceDefInnerPair',['../classyoi_1_1interfaceDefInnerPair.html',1,'yoi']]],
  ['interfacedefstmt_35',['interfaceDefStmt',['../classyoi_1_1interfaceDefStmt.html',1,'yoi']]],
  ['invocationarguments_36',['invocationArguments',['../classyoi_1_1invocationArguments.html',1,'yoi']]],
  ['ir_37',['IR',['../classyoi_1_1IR.html',1,'yoi']]],
  ['irbuildconfig_38',['IRBuildConfig',['../structyoi_1_1IRBuildConfig.html',1,'yoi']]],
  ['irbuilder_39',['IRBuilder',['../classyoi_1_1IRBuilder.html',1,'yoi']]],
  ['ircodeblock_40',['IRCodeBlock',['../classyoi_1_1IRCodeBlock.html',1,'yoi']]],
  ['irdebuginfo_41',['IRDebugInfo',['../structyoi_1_1IRDebugInfo.html',1,'yoi']]],
  ['irenumerationtype_42',['IREnumerationType',['../classyoi_1_1IREnumerationType.html',1,'yoi']]],
  ['irexternentry_43',['IRExternEntry',['../classyoi_1_1IRExternEntry.html',1,'yoi']]],
  ['irffitable_44',['IRFFITable',['../classyoi_1_1IRFFITable.html',1,'yoi']]],
  ['irfunctiondefinition_45',['IRFunctionDefinition',['../classyoi_1_1IRFunctionDefinition.html',1,'yoi']]],
  ['irfunctionoptimizer_46',['IRFunctionOptimizer',['../classyoi_1_1IRFunctionOptimizer.html',1,'yoi']]],
  ['irfunctiontemplate_47',['IRFunctionTemplate',['../classyoi_1_1IRFunctionTemplate.html',1,'yoi']]],
  ['irinterfaceimplementationdefinition_48',['IRInterfaceImplementationDefinition',['../classyoi_1_1IRInterfaceImplementationDefinition.html',1,'yoi']]],
  ['irinterfaceimplementationtemplate_49',['IRInterfaceImplementationTemplate',['../classyoi_1_1IRInterfaceImplementationTemplate.html',1,'yoi']]],
  ['irinterfaceinstancedefinition_50',['IRInterfaceInstanceDefinition',['../classyoi_1_1IRInterfaceInstanceDefinition.html',1,'yoi']]],
  ['irinterfaceinstancetemplate_51',['IRInterfaceInstanceTemplate',['../classyoi_1_1IRInterfaceInstanceTemplate.html',1,'yoi']]],
  ['irlinker_52',['IRLinker',['../classyoi_1_1IRLinker.html',1,'yoi']]],
  ['irmodule_53',['IRModule',['../classyoi_1_1IRModule.html',1,'yoi']]],
  ['irobjectfile_54',['IRObjectFile',['../classyoi_1_1IRObjectFile.html',1,'yoi']]],
  ['iroperand_55',['IROperand',['../classyoi_1_1IROperand.html',1,'yoi']]],
  ['iroptimizer_56',['IROptimizer',['../classyoi_1_1IROptimizer.html',1,'yoi']]],
  ['irstringliteralpool_57',['IRStringLiteralPool',['../classyoi_1_1IRStringLiteralPool.html',1,'yoi']]],
  ['irstructdefinition_58',['IRStructDefinition',['../classyoi_1_1IRStructDefinition.html',1,'yoi']]],
  ['irstructtemplate_59',['IRStructTemplate',['../classyoi_1_1IRStructTemplate.html',1,'yoi']]],
  ['irtemplatebuilder_60',['IRTemplateBuilder',['../classyoi_1_1IRTemplateBuilder.html',1,'yoi']]],
  ['irtypealias_61',['IRTypeAlias',['../classyoi_1_1IRTypeAlias.html',1,'yoi']]],
  ['irvaluetype_62',['IRValueType',['../classyoi_1_1IRValueType.html',1,'yoi']]],
  ['irvariabletable_63',['IRVariableTable',['../classyoi_1_1IRVariableTable.html',1,'yoi']]],
  ['is_5freflected_64',['is_reflected',['../structmagic__enum_1_1detail_1_1is__reflected.html',1,'magic_enum::detail']]],
  ['is_5fscoped_5fenum_65',['is_scoped_enum',['../structmagic__enum_1_1detail_1_1is__scoped__enum.html',1,'is_scoped_enum&lt; T, bool &gt;'],['../structmagic__enum_1_1is__scoped__enum.html',1,'is_scoped_enum&lt; T &gt;']]],
  ['is_5fscoped_5fenum_3c_20t_2c_20true_20_3e_66',['is_scoped_enum&lt; T, true &gt;',['../structmagic__enum_1_1detail_1_1is__scoped__enum_3_01T_00_01true_01_4.html',1,'magic_enum::detail']]],
  ['is_5funscoped_5fenum_67',['is_unscoped_enum',['../structmagic__enum_1_1detail_1_1is__unscoped__enum.html',1,'is_unscoped_enum&lt; T, bool &gt;'],['../structmagic__enum_1_1is__unscoped__enum.html',1,'is_unscoped_enum&lt; T &gt;']]],
  ['is_5funscoped_5fenum_3c_20t_2c_20true_20_3e_68',['is_unscoped_enum&lt; T, true &gt;',['../structmagic__enum_1_1detail_1_1is__unscoped__enum_3_01T_00_01true_01_4.html',1,'magic_enum::detail']]],
  ['item_69',['Item',['../structyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item.html',1,'yoi::IRFunctionOptimizer::SimulationStack']]],
  ['iterator_70',['iterator',['../classyoi_1_1enum__range_1_1iterator.html',1,'enum_range&lt; enumT, TSize &gt;::iterator'],['../classyoi_1_1indexTable_1_1iterator.html',1,'indexTable&lt; A, B &gt;::iterator'],['../classyoi_1_1indexTableDeprecated_1_1iterator.html',1,'indexTableDeprecated&lt; A, B &gt;::iterator'],['../structyoi_1_1IRFunctionOptimizer_1_1SimulationStack_1_1Item_1_1ContributedInstructionSet_1_1Iterator.html',1,'IRFunctionOptimizer::SimulationStack::Item::ContributedInstructionSet::Iterator']]]
];
