var searchData=
[
  ['i_20o_20in_20hoshi_20lang_0',['Console I/O in Hoshi-lang',['../md_docs_2Console.html',1,'']]],
  ['implementation_20of_20null_20literal_20in_20hoshi_20lang_1',['The implementation of null literal in hoshi-lang',['../md_docs_2Null.html',1,'']]],
  ['in_20hoshi_20lang_2',['in hoshi lang',['../md_docs_2Console.html',1,'Console I/O in Hoshi-lang'],['../md_docs_2File_01System.html',1,'File System in Hoshi-lang'],['../md_docs_2Finalizers.html',1,'Finalizers in Hoshi-lang'],['../md_docs_2HashMap.html',1,'HashMap in Hoshi-lang'],['../md_docs_2JSON.html',1,'JSON in Hoshi-lang'],['../md_docs_2Macros.html',1,'Macros in Hoshi-lang'],['../md_docs_2Math.html',1,'Math in Hoshi-lang'],['../md_docs_2Result.html',1,'Result Type in Hoshi-lang'],['../md_docs_2Runtime.html',1,'Runtime in Hoshi-lang'],['../md_docs_2String.html',1,'String in Hoshi-lang'],['../md_docs_2Structured_01Bindings.html',1,'Structured Bindings in Hoshi-lang'],['../md_docs_2Null.html',1,'The implementation of null literal in hoshi-lang'],['../md_docs_2Threading.html',1,'Threading in Hoshi-lang'],['../md_docs_2Type_01Aliases.html',1,'Type Aliases in Hoshi-lang'],['../md_docs_2Vector.html',1,'Vector in Hoshi-lang']]],
  ['interface_20allocation_20and_20virtual_20invocation_20reduction_20接口分配和虚函数调用消除优化策略_3',['The Optimization Strategy of Interface Allocation and Virtual Invocation Reduction 接口分配和虚函数调用消除优化策略',['../md_docs_2The_01Optimization_01Strategy_01of_01Interface_01Allocation_01and_01Virtual_01Invocation_01Reduction.html',1,'']]],
  ['intermediate_20representation_20ir_20handbook_4',['The Hoshi-lang Intermediate Representation (IR) Handbook',['../md_docs_2IR.html',1,'']]],
  ['invocation_20reduction_20接口分配和虚函数调用消除优化策略_5',['The Optimization Strategy of Interface Allocation and Virtual Invocation Reduction 接口分配和虚函数调用消除优化策略',['../md_docs_2The_01Optimization_01Strategy_01of_01Interface_01Allocation_01and_01Virtual_01Invocation_01Reduction.html',1,'']]],
  ['ir_20handbook_6',['The Hoshi-lang Intermediate Representation (IR) Handbook',['../md_docs_2IR.html',1,'']]]
];
