#ifndef BUILD_CONFIG_H
#define BUILD_CONFIG_H

#define HOSHI_LANG_SDK_VERSION = "1"
#define ELYSIA_RUNTIME_BUILD_TYPE_DEBUG
#define ELYSIA_RUNTIME_ENABLE_BUILTIN_MEMORY_LEAK_DETECTOR
#define ELYSIA_RUNTIME_BUILD_PRESERVE_BASIC_INFORMATION

#endif // BUILD_CONFIG_H